version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/green_app_demo
hooks:
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ec2-user  
    - location: scripts/build_deploy.sh
      timeout: 300
      runas: ec2-user
    - location: scripts/start.sh
      timeout: 300
      runas: ec2-user
