version: 0.0
os: linux
files:
  - source: .
    destination: /home/ec2-user/green_app_demo
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: root
  Install:  
    - location: scripts/build_deploy
      timeout: 300
  AfterInstall:
    - location: scripts/cleanup
      timeout: 300
  ApplicationStart:
    - location: scripts/start
      timeout: 300
