#!/bin/bash
sudo chown -R ec2-user /home/ec2-user/green_app_demo
cd /home/ec2-user/green_app_demo/complete
gradle build
sudo cp /home/ec2-user/green_app_demo/complete/build/libs/green_app-0.1.0.jar /home/ec2-user/

