#!/bin/bash
sudo yum update -y && install -y
sudo yum remove jre-1.7.0 -y
sudo yum install java-1.8.0-openjdk-devel -y
sudo rm -rf /opt/gradle/
sudo mkdir /opt/gradle/
export gradle_version=4.6
wget -c http://services.gradle.org/distributions/gradle-${gradle_version}-all.zip
sudo unzip  gradle-${gradle_version}-all.zip -d /opt/gradle
sudo echo "export PATH=$PATH:/opt/gradle/gradle-4.6/bin" >> /home/ec2-user/.bashrc
source /home/ec2-user/.bashrc
sudo rm -rf /home/ec2-user/red_app_demo
