#!/bin/bash
sudo yum update && install -y
sudo yum remove jre-1.7.0 -y
sudo yum install java-1.8.0-openjdk-devel -y
sudo rm /home/ec2-user/gradle-4.6-all.zip
export gradle_version=4.6
cd /home/ec2-user/
wget -c http://services.gradle.org/distributions/gradle-${gradle_version}-all.zip
sudo chown -R ec2-user /opt/gradle/
sudo unzip  gradle-${gradle_version}-all.zip -d /opt/gradle/
sudo echo "export PATH=$PATH:/opt/gradle/gradle-4.6/bin" >> /home/ec2-user/.bashrc
source /home/ec2-user/.bashrc

